### ISSUE TITLE
Deal with corrupted database files

### ISSUE THREAD

**Issue by ChrisTerBeke** [PRINTR3D/formide-client#101]
Sometimes, a database file can get corrupted when for example the network connection goes down halfway a transaction. We should deal with this property. Access tokens have the most issues with this.

**Comment by jthunnissen** [comment]
"In MongoDB, a write operation is atomic on the level of a single document, even if the operation modifies multiple embedded documents within a single document."
Dat zou dus niet moeten kunnen aldus de Mongo handleiding.
