### ISSUE TITLE
Smaller API differences

### ISSUE THREAD

**Issue by regnerus** [PRINTR3D/formide-client#116]
I will list the differences I find between the Formide API and the client API here.

- [x] `/api/files/upload` response `uploadedFile` is called `file`.
- [ ] `Cannot POST /api/db/files/:id/images/base64`

**Comment by ChrisTerBeke** [comment]
Cool. We'll fix them all in one go later today, probably in the client

**Comment by ChrisTerBeke** [comment]
Fixed uploadedFile
