### ISSUE TITLE
Add WIFI endpoints

### ISSUE THREAD

**Issue by karimcitoh** [PRINTR3D/formide-client#166]
It would be nice to set the wifi from the UI.
Also, to show in the display if the wifi is connected, since there is a status icon for this.

**Comment by ChrisTerBeke** [comment]
I can add an endpoint that fetches the wifi status. Connecting to wifi is already possible via an endpoint, will add documentation.

**Comment by karimcitoh** [comment]
nice, then I can probably add this today
