### ISSUE TITLE
The setup wifi page does not automatically refresh its ssid list

### ISSUE THREAD

**Issue by jthunnissen** [PRINTR3D/formide-client#185]
The dropdown list should automatically be updated with the results of a periodic network scan and the user should be notified of this. Right now I often have to refresh the page a couple of times before the Printr network is visible.

**Comment by ChrisTerBeke** [comment]
We want to keep the page as simple as possible with not too much javascript fanciness that can only break.

**Comment by jthunnissen** [comment]
Addition of a simple "refresh list" button next to the ssid selector which just reloads the whole page, would do the trick. No javascript fanciness required.

**Comment by ChrisTerBeke** [comment]
@regnerus can you pick this up?
