### ISSUE TITLE
Issue with settings queue item state after manually stopping or stopping from printer side

### ISSUE THREAD

**Issue by ChrisTerBeke** [PRINTR3D/formide-client#89]
They stay 'printing' so multiple items show up as active print job when the printer is printing.

**Comment by ChrisTerBeke** [comment]
Fixed in 0.2.16. Setting all items for the selected printer (port) to 'queued' before starting the new print.

**Comment by regnerus** [comment]
According to this (https://github.com/PRINTR3D/formide-interface/issues/326) issue this is still (or again) an issue.
