### ISSUE TITLE
Send file size of gcode file to drivers

### ISSUE THREAD

**Issue by karimcitoh** [PRINTR3D/formide-client#93]
By knowing the file size of a gcode file, driver can make sure the file is downloaded completely before starting buffering it.

**Comment by ChrisTerBeke** [comment]
I have a better plan. I'll only show a print job in the queue when the file is fully downloaded. This way, the driver doesn't have to check anything :)

**Comment by karimcitoh** [comment]
That'd be the best option indeed.
